GaebalLog/GaebalLog_front

- src/components/header/Header.tsx
- src/constants/global/atoms.ts
- src/hooks/useResetHandler.tsx
- src/utils/util-scrollhandler.ts
> [FEAT] 유틸 함수 및 커스텀 훅 생성

- src/components/commonUI/Discussion.tsx
- src/components/commonUI/Post.tsx
[FEAT] Discussion 컴포넌트 인터렉션 추가
> [FEAT] Discussion 컴포넌트 인터렉션 추가

- src/components/designSystem/Input.tsx
- src/components/provider/Provider.tsx
- src/components/provider/SettingsProvider.tsx
- src/hooks/useModalController.ts
- src/utils/util-scrollhandler.ts
> [FEAT] 검색 바 드롭다운(디자인 변경사항) 구현

- .babelrc
- package-lock.json
- package.json
- src/app/layout.tsx
- src/components/VoiceSearch.tsx
- src/components/commonUI/LiveSearchInput.tsx
- src/components/designSystem/Input.tsx
- src/components/header/Header.tsx
- src/components/provider/Provider.tsx
- src/components/provider/SettingsProvider.tsx
- src/hooks/useIcon.tsx
- src/hooks/useModalController.ts
> [FEAT] 음성인식 자동검색 기능 구현

- jest.config.js
- jest.setup.js
- package-lock.json
- package.json
- src/tests/units/Auth.test.tsx
- src/tests/units/Detail.test.tsx
[FIX] regenerator-runtime 테스트 반영
> [FIX] regenerator-runtime 테스트 반영

- src/app/layout.tsx
- src/components/provider/SettingsProvider.tsx
> [FIX] 레이아웃 에러 수정

- .github/workflows/setting.yml
- package.json
> [CHORE] 깃허브 액션 설정

- src/components/designSystem/Button.tsx
[FIX] 토의 검색 결과 페이지에 키워드 부분 스크롤 생기던 것 수정
> [FIX] 토의 검색 결과 페이지에 키워드 부분 스크롤 생기던 것 수정

- src/components/header/Header.tsx
> [FIX] 헤더 로고 레이아웃 변경에 따른 버그 수정

- src/app/home/page.tsx
- src/components/commonUI/LoggedSideBar.tsx
- src/components/commonUI/StickyStyle.tsx
- src/components/discussion/DiscussionSideBar.tsx
- src/components/tech/TechSideBar.tsx
[FIX] 사이드 바 sticky 이슈 수정, 기능정의에 따른 일부 컴포넌트 수정
> [FIX] 사이드 바 sticky 이슈 수정, 기능정의에 따른 일부 컴포넌트 수정

- .eslintrc.json
- src/app/mypage/page.tsx
- src/app/post/[...slug]/page.tsx
- src/components/provider/withAuth.tsx
[FEAT] 글 작성 페이지에 로그인 인증 로직 추가(HOC 호환성 향상을 위한 코드 수정)
> [FEAT] 글 작성 페이지에 로그인 인증 로직 추가(HOC 호환성 향상을 위한 코드 수정)

- src/components/mypage/article/MyInfo.tsx
- src/tests/units/Mypage.test.tsx
> [FEAT] 마이페이지 테스트 코드 작성(1차 완료)

- src/api/postAPI.ts
- src/app/home/page.tsx
- src/app/post/create/[...type]/page.tsx
- src/app/post/update/[...articleId]/page.tsx
- src/app/post/update/page.tsx
- src/app/tech/[postId]/page.tsx
- src/components/discussion/DiscussionSideBar.tsx
- src/components/discussionDetail/RoomContents.tsx
- src/components/header/Header.tsx
- src/components/post/AddTagInput.tsx
- src/components/post/PostEditor.tsx
- src/components/provider/Provider.tsx
- src/components/tech/TechSideBar.tsx
- src/tests/msw/postHanlder.ts
- src/tests/units/Discussion.test.tsx
- src/tests/units/DiscussionRoom.test.tsx
- src/tests/units/Home.test.tsx
- src/tests/units/Post.test.tsx
> [FEAT] 글 작성, 수정 기능 작업(서버 연동)

- src/@types/index.d.ts
- src/api/postAPI.ts
- src/app/api/posts/all/route.tsx
- src/app/discussion/page.tsx
- src/app/home/page.tsx
- src/app/tech/[postId]/page.tsx
- src/app/tech/page.tsx
- src/components/commonUI/Post.tsx
- src/components/commonUI/SortBar.tsx
- src/components/mypage/article/MyWritten.tsx
- src/components/mypage/article/Mydiscussions.tsx
- src/components/observing/InfiniteScroll.tsx
- src/components/profile/article/UserTech.tsx
- src/tests/msw/postHanlder.ts
- src/tests/msw/restHandler.ts
> [FEAT] 무한스크롤 구현

- src/components/post/CustomNumberInput.tsx
- src/components/post/TimeSetting.tsx
- src/components/post/calendar/Calendar.tsx
- src/components/post/calendar/Days.tsx
- src/components/post/calendar/Header.tsx
- src/tests/units/Post.test.tsx
> [FEAT] 토의 시간 설정 모달 작업

- src/components/commonUI/Post.tsx
- tailwind.config.js
> [FIX] 글 목록 컴포넌트 eclipsis 적용

- src/api/postAPI.ts
- src/app/tech/[postId]/page.tsx
- src/components/commonUI/Post.tsx
- src/tests/__mocks__/IntersectionObserverMock.ts
- src/tests/msw/postHanlder.ts
- src/tests/units/Tech.test.tsx
- src/utils/util-datetime.ts
[FIX] 글 목록 시간 유틸함수 수정, [FEAT] intersectionObserver 모킹
> [FIX] 글 목록 시간 유틸함수 수정, [FEAT] intersectionObserver 모킹

- src/@types/index.d.ts
- src/api/postAPI.ts
- src/app/api/posts/all/route.tsx
- src/app/discussion/page.tsx
- src/app/globals.css
- src/app/home/page.tsx
- src/app/post/create/[...type]/page.tsx
- src/app/post/update/[...articleId]/page.tsx
- src/app/tech/[postId]/page.tsx
- src/app/tech/page.tsx
- src/components/commonUI/Post.tsx
- src/components/detail/Contents.tsx
- src/constants/global/querykeys.ts
- src/hooks/postAPI/useGetPost.ts
- src/tests/msw/postHanlder.ts
- src/tests/msw/restHandler.ts
- src/tests/units/Home.test.tsx
- src/utils/util-datetime.ts
- src/utils/util-decodeImg.ts
- src/utils/util-extractImage.ts
- src/utils/util-replaceImg.ts
[FEAT] post 기능 구현(북마크, img/content 분리, 정렬 기능)
> [FEAT] post 기능 구현(북마크, img/content 분리, 정렬 기능)

- src/api/postAPI.ts
- src/app/home/page.tsx
- src/app/tech/page.tsx
- src/components/commonUI/Post.tsx
- src/hooks/postAPI/useToggleBookmark.ts
- src/hooks/postAPI/useToggleLike.ts
[FEAT] 좋아요 기능 구현(어뷰징 방지 작업 제외)
> [FEAT] 좋아요 기능 구현(어뷰징 방지 작업 제외)

- src/api/authAPI.ts
- src/app/auth/login/page.tsx
- src/app/auth/signup/page.tsx
- src/components/mypage/article/MyInfo.tsx
- src/components/profile/ProfileSidebar.tsx
- src/components/provider/SettingsProvider.tsx
- src/constants/global/atoms.ts
- src/tests/msw/authHandler.ts
> [FEAT] 인증 관련 API 추가

- src/utils/util-datetime.ts
[FIX] DB 날짜 데이터 값 잘못된 값 검사 로직 추가
> [FIX] DB 날짜 데이터 값 잘못된 값 검사 로직 추가

- src/app/tech/[postId]/page.tsx
- src/components/commonUI/LikeView.tsx
- src/components/commonUI/Post.tsx
> [FEAT] 상세페이지 디자인 추가 반영

- package-lock.json
- package.json
- src/app/globals.css
- src/app/layout.tsx
- src/app/not-found.tsx
- src/app/post/create/[...type]/page.tsx
- src/app/post/update/[...articleId]/page.tsx
- src/components/commonUI/Discussion.tsx
- src/components/commonUI/LoggedSideBar.tsx
- src/components/commonUI/Post.tsx
- src/components/commonUI/SideBar.tsx
- src/components/designSystem/Button.tsx
- src/components/detail/form/CommentForm.tsx
- src/components/detail/form/SubCommentForm.tsx
- src/components/discussion/DiscussionSideBar.tsx
- src/components/discussionDetail/DiscussionProgress.tsx
- src/components/discussionDetail/RoomContents.tsx
- src/components/modal/keywordSearch/KeywordList.tsx
- src/components/post/AddTagInput.tsx
- src/components/post/CustomNumberInput.tsx
- src/components/tech/TechSideBar.tsx
> [FIX] 다크 모드 색상 변경 작업

- src/@types/index.d.ts
- src/api/postAPI.ts
- src/app/tech/[postId]/page.tsx
- src/hooks/featureBtn/updateBtn.tsx
- src/tests/msw/postHanlder.ts
- src/tests/units/Detail.test.tsx
> [FEAT] 유저인증에 따른 버튼 노출

- src/api/authAPI.ts
- src/app/auth/callback/[...snsType]/page.tsx
- src/app/auth/login/page.tsx
- src/app/auth/signup/page.tsx
- src/app/globals.css
- src/components/designSystem/Input.tsx
- src/components/designSystem/Toggle.tsx
- src/components/signup/InputWithCheck.tsx
- src/tests/msw/authHandler.ts
- src/tests/units/Login.test.tsx
[FEAT] 다크 모드 디자인과 다른던 부분들 수정 [TEST] 소셜 로그인 테스트 추가
> [FEAT] 다크 모드 디자인과 다른던 부분들 수정 [TEST] 소셜 로그인 테스트 추가

- next.config.js
- src/api/authAPI.ts
- src/app/auth/signup/page.tsx
- src/components/commonUI/EditBtn.tsx
- src/components/commonUI/LoggedSideBar.tsx
- src/components/commonUI/SideBar.tsx
- src/components/designSystem/Input.tsx
- src/components/modal/keywordSearch/KeywordSearch.tsx
- src/components/mypage/article/MyInfo.tsx
- src/components/mypage/article/MyPageCategory.tsx
- src/components/signup/InputWithCheck.tsx
- src/hooks/usePagination.ts
- src/tests/units/Mypage.test.tsx
- src/tests/units/Signup.test.tsx
[FEAT] 마이페이지 프로필 API 연결 [FEAT] 레이아웃에 바뀐 디자인 적용
> [FEAT] 마이페이지 프로필 API 연결 [FEAT] 레이아웃에 바뀐 디자인 적용

- src/tests/units/hooks/useValidation.test.tsx
[CHORE] 테스트 코드 구조 유닛 단위 디렉토링으로 변경
> [CHORE] 테스트 코드 구조 유닛 단위 디렉토링으로 변경

- src/components/detail/comment/element/btn/CreateCommentBtn.tsx
- src/components/detail/comment/element/card/CommentCard.tsx
- src/components/detail/comment/element/textarea/CommentForm.tsx
- src/components/detail/comment/element/textarea/SubCommentForm.tsx
- src/hooks/commentAPI/useCreateComment.tsx
- src/hooks/commentAPI/useDeleteComment.tsx
- src/hooks/commentAPI/useUpdateComment.tsx
> [FIX] 댓글 수정 후 렌더링 개선

- src/components/detail/comment/element/btn/CreateCommentBtn.tsx
- src/components/detail/comment/element/card/CommentCard.tsx
- src/components/detail/comment/element/textarea/CommentForm.tsx
- src/components/detail/comment/element/textarea/SubCommentForm.tsx
> [FEAT] 댓글 작성 이후 각종 초기화 작업 완료

- src/@types/index.d.ts
- src/api/authAPI.ts
- src/app/auth/callback/[snsType]/page.tsx
- src/app/auth/forgotPassword/page.tsx
- src/app/discussion/page.tsx
- src/app/home/page.tsx
- src/app/tech/page.tsx
- src/components/auth/input/InputEmailCodeCheck.tsx
- src/components/auth/input/InputWithSendEmail.tsx
- src/components/commonUI/ResultNotFound.tsx
- src/components/commonUI/SideBar.tsx
- src/components/designSystem/Input.tsx
- src/components/designSystem/Toggle.tsx
- src/components/header/Header.tsx
- src/constants/global/atoms.ts
- src/hooks/authAPI/useCheckDuplicacy.ts
- src/hooks/authAPI/useLoginSubmit.ts
- src/hooks/authAPI/useSignupSubmit.ts
- src/hooks/discussionAPI/useGetDiscussion.ts
- src/hooks/liveSearch/useLiveSearchController.ts
- src/hooks/postAPI/useGetPost.ts
- src/utils/util-errorCase.ts
> [FEAT] 예외 처리 추가

- src/components/designSystem/Toggle.tsx
- src/hooks/authAPI/useCheckDuplicacy.ts
- src/tests/msw/authHandler.ts
> [FIX] 테스트, 빌드 오류 수정
